const CATEGORIES = {
    fitness: {
        title: "Fitness",
        color: "#ddd6ff",
        seo: {
            title: "Pretty Calculators - Fitness Calculators",
            description: "Free fitness calculators at Pretty Calculators. BMI, BMR, TDEE, Body Fat, Ideal Weight — beautifully designed and fast.",
        },
        tools: [
            { label: "BMI Calculator", to: "/fitness/bmi-calculator" },
            { label: "Body Fat Calculator", to: "/fitness/body-fat-calculator" },
            { label: "BMR Calculator", to: "/fitness/bmr-calculator" },
            { label: "TDEE Calculator", to: "/fitness/tdee-calculator" },
            { label: "Ideal Weight Calculator", to: "/fitness/ideal-weight-calculator" },
            { label: "One Rep Max Calculator", to: "/fitness/one-rep-max-calculator" },
            { label: "Protein Calculator", to: "/fitness/protein-calculator" },
            { label: "Macro Calculator",   to: "/fitness/macro-calculator" },
            { label: "Pace Calculator",            to: "/fitness/pace-calculator" },
            { label: "Calories Burned Calculator", to: "/fitness/calories-burned-calculator" },
            { label: "Lean Body Mass Calculator",  to: "/fitness/lean-body-mass-calculator" },
            { label: "Calorie Deficit Calculator", to: "/fitness/calorie-deficit-calculator" },
            { label: "VO2 Max Calculator",          to: "/fitness/vo2-max-calculator" },
            { label: "Heart Rate Zone Calculator",  to: "/fitness/heart-rate-zone-calculator" },
            { label: "Water Intake Calculator",     to: "/fitness/water-intake-calculator" },
        ],
    },
    math: {
        title: "Math",
        color: "#f5e642",
        seo: {
            title: "Pretty Calculators - Math Calculators",
            description: "Free math calculators at Pretty Calculators. Percentage, Manhattan Distance and more — beautifully designed and fast.",
        },
        tools: [
            { label: "Percentage Calculator", to: "/math/percentage-calculator" },
            { label: "Fraction Calculator", to: "/math/fraction-calculator" },
            { label: "Average Calculator", to: "/math/average-calculator" },
            { label: "Random Number Generator", to: "/math/random-number-generator" },
            { label: "Quadratic Formula Calculator", to: "/math/quadratic-formula-calculator" },
            { label: "Ratio Calculator", to: "/math/ratio-calculator" },
            { label: "Standard Deviation Calculator",  to: "/math/standard-deviation-calculator" },
            { label: "Cosine Similarity Calculator",   to: "/math/cosine-similarity-calculator" },
            { label: "Dot Product Calculator",         to: "/math/dot-product-calculator" },
            { label: "Manhattan Distance Calculator",  to: "/math/manhattan-distance-calculator" },
            { label: "Euclidean Distance Calculator",  to: "/math/euclidean-distance-calculator" },
            { label: "Chebyshev Distance Calculator",  to: "/math/chebyshev-distance-calculator" },
            { label: "Hamming Distance Calculator",    to: "/math/hamming-distance-calculator" },
            { label: "Minkowski Distance Calculator",  to: "/math/minkowski-distance-calculator" },
            { label: "GPA Calculator",                 to: "/math/gpa-calculator" },
            { label: "LCM & GCF Calculator",           to: "/math/lcm-gcf-calculator" },
            { label: "Scientific Notation Calculator", to: "/math/scientific-notation-calculator" },
        ],
    },
    finance: {
        title: "Finance",
        color: "#d4edda",
        seo: {
            title: "Pretty Calculators - Finance Calculators",
            description: "Free finance calculators at Pretty Calculators. YouTube earnings, TikTok income, compound interest, debt payoff, savings goals and take-home pay — practical money tools.",
        },
        tools: [
            { label: "YouTube Earnings Calculator",  to: "/finance/youtube-earnings-calculator" },
            { label: "TikTok Earnings Calculator",   to: "/finance/tiktok-earnings-calculator" },
            { label: "Compound Interest Calculator", to: "/finance/compound-interest-calculator" },
            { label: "Debt Payoff Calculator",       to: "/finance/debt-payoff-calculator" },
            { label: "Savings Goal Calculator",      to: "/finance/savings-goal-calculator" },
            { label: "Take-Home Pay Calculator",     to: "/finance/take-home-pay-calculator" },
            { label: "Mortgage Calculator",             to: "/finance/mortgage-calculator" },
            { label: "Loan Calculator",                 to: "/finance/loan-calculator" },
            { label: "Credit Card Payoff Calculator",   to: "/finance/credit-card-payoff-calculator" },
            { label: "Investment Calculator",           to: "/finance/investment-calculator" },
            { label: "Retirement Calculator",           to: "/finance/retirement-calculator" },
            { label: "Income Tax Calculator",           to: "/finance/income-tax-calculator" },
            { label: "Salary to Hourly Calculator",     to: "/finance/salary-to-hourly-calculator" },
            { label: "ROI Calculator",                  to: "/finance/roi-calculator" },
            { label: "Break-Even Calculator",           to: "/finance/break-even-calculator" },
            { label: "VAT Calculator",                  to: "/finance/vat-calculator" },
            { label: "Net Worth Calculator",            to: "/finance/net-worth-calculator" },
        ],
    },
    tools: {
        title: "Tools",
        color: "#cfe8ff",
        seo: {
            title: "Pretty Calculators - Free Online Tools",
            description: "Free online tools that run in your browser — image compressor, QR code generator, password generator, JSON formatter, diff checker and more. Private: nothing is uploaded.",
        },
        tools: [
            { label: "Image Compressor", to: "/tools/image-compressor" },
            { label: "QR Code Generator", to: "/tools/qr-code-generator" },
            { label: "Password Generator", to: "/tools/password-generator" },
            { label: "JSON Formatter", to: "/tools/json-formatter" },
            { label: "Diff Checker", to: "/tools/diff-checker" },
            { label: "Word Counter", to: "/tools/word-counter" },
            { label: "Unix Timestamp Converter", to: "/tools/unix-timestamp-converter" },
            { label: "Base64 Encoder / Decoder", to: "/tools/base64-encoder-decoder" },
            { label: "UUID Generator", to: "/tools/uuid-generator" },
            { label: "Lorem Ipsum Generator", to: "/tools/lorem-ipsum-generator" },
            { label: "URL Encoder / Decoder", to: "/tools/url-encoder-decoder" },
            { label: "Text Case Converter", to: "/tools/text-case-converter" },
            { label: "CSV to JSON Converter", to: "/tools/csv-to-json-converter" },
            { label: "Color Contrast Checker", to: "/tools/color-contrast-checker" },
            { label: "Px to Rem Calculator", to: "/tools/px-to-rem-calculator" },
            { label: "Aspect Ratio Calculator", to: "/tools/aspect-ratio-calculator" },
            { label: "CSS clamp() Calculator", to: "/tools/css-clamp-calculator" },
        ],
    },
    other: {
        title: "Other",
        color: "#ffd6d6",
        seo: {
            title: "Pretty Calculators - Other Calculators & Converters",
            description: "Free utility calculators and unit converters at Pretty Calculators. Age, Sleep, Tip, Pizza, and temperature/distance/weight converters — fast and free.",
        },
        tools: [
            { label: "Age Calculator", to: "/other/age-calculator" },
            { label: "Aqua Calculator", to: "/other/aqua-calculator" },
            { label: "Pizza Calculator", to: "/other/pizza-calculator" },
            { label: "Tip Calculator", to: "/other/tip-calculator" },
            { label: "Sleep Calculator", to: "/other/sleep-calculator" },
            { label: "Celsius to Fahrenheit", to: "/unit/celsius-to-fahrenheit-converter" },
            { label: "Fahrenheit to Celsius", to: "/unit/fahrenheit-to-celsius-converter" },
            { label: "Miles to Kilometers", to: "/unit/miles-to-kilometers" },
            { label: "Kilometers to Miles", to: "/unit/kilometers-to-miles" },
            { label: "Inches to CM", to: "/unit/inches-to-cm-converter" },
            { label: "KG to LBS", to: "/unit/kg-to-lbs-converter" },
            { label: "Feet to Meters", to: "/unit/feet-to-meters-converter" },
            { label: "Pregnancy Due Date Calculator", to: "/other/pregnancy-due-date-calculator" },
            { label: "Ovulation Calculator",          to: "/other/ovulation-calculator" },
            { label: "Discount Calculator",           to: "/other/discount-calculator" },
            { label: "Reading Time Calculator",       to: "/other/reading-time-calculator" },
        ],
    },
};

export const useCategoryConfig = (slug) => {
    const config = CATEGORIES[slug] ?? null;

    const otherCategories = Object.entries(CATEGORIES)
        .filter(([key]) => key !== slug)
        .map(([key, val]) => ({ slug: key, ...val }));

    return { config, otherCategories };
};
