<template>
    <UiCalcPage title="ROI Calculator" category="finance" description-title="Return on investment, net profit, and annualised return">
        <template #calc>
            <CalculatorsFinanceRoiCalc />
        </template>
        <template #facts>
            <CalcFact label="Formula"    value="(Gain − Cost) / Cost" />
            <CalcFact label="Good ROI"   value="Depends on asset class" />
            <CalcFact label="S&P 500"    value="~10% per year (avg)" />
            <CalcFact label="CAGR"       value="Annualised growth rate" />
        </template>
        <template #description>
            <p>
                The <strong>ROI Calculator</strong> (Return on Investment) measures how much profit or loss you made relative to your initial investment. Enter your starting cost and final value to instantly see your ROI percentage, net profit, and — if you provide a time period — the annualised ROI and CAGR.
            </p>
            <h3>ROI formula</h3>
            <p>
                <strong>ROI (%) = (Final Value − Initial Investment) / Initial Investment × 100</strong>
            </p>
            <p>
                A 50% ROI means you gained 50 cents for every dollar invested. A negative ROI means you lost money.
            </p>
            <h3>Annualised ROI vs CAGR</h3>
            <p>
                <strong>Annualised ROI</strong> divides the total ROI by the number of years — simple but ignores compounding. <strong>CAGR</strong> (Compound Annual Growth Rate) is the rate at which an investment would have grown if it compounded at the same rate each year. CAGR is a better measure of true investment performance over multi-year periods.
            </p>
            <p>
                CAGR formula: <strong>(Final / Initial)^(1/years) − 1</strong>.
            </p>
            <p>
                For longer-term wealth modelling, pair this with our <NuxtLink to="/finance/compound-interest-calculator">compound interest calculator</NuxtLink>.
            </p>
        </template>
        <template #example>
            <p>You invested <strong>$10,000</strong> in a stock. After <strong>3 years</strong> it's worth <strong>$14,500</strong>.</p>
            <p><strong>ROI</strong> = (14,500 − 10,000) / 10,000 × 100 = <strong>45%</strong>.</p>
            <p><strong>Net profit</strong>: $4,500.</p>
            <p><strong>Annualised ROI</strong>: 45% / 3 = 15% per year (simple).</p>
            <p><strong>CAGR</strong>: (14,500 / 10,000)^(1/3) − 1 = 1.45^0.333 − 1 ≈ <strong>13.2% per year</strong> (compounded). The CAGR is lower than simple annualised ROI because it accounts for the effect of compounding.</p>
        </template>
        <template #faq>
            <CalcFaq :faqs="faqs" />
        </template>
    </UiCalcPage>
</template>

<script setup>
definePageMeta({ layout: 'brutalist' })

const faqs = [
    { q: "What is ROI?", a: "ROI (Return on Investment) is a percentage that measures the profit or loss on an investment relative to its cost. ROI = (Final Value − Initial Cost) / Initial Cost × 100. A 20% ROI means you earned $20 for every $100 invested." },
    { q: "What is a good ROI?", a: "It depends on the asset class and risk. The S&P 500 averages about 10% per year before inflation. Real estate averages 7–10%. A business investment with 15–30% annual ROI is considered strong. Savings accounts currently offer 4–5%. Higher expected ROI always comes with higher risk." },
    { q: "What is the difference between ROI and CAGR?", a: "ROI measures total return over the full period without regard to time. CAGR (Compound Annual Growth Rate) expresses that same return as an equivalent annual compounded rate. For a 45% ROI over 3 years: CAGR ≈ 13.2%, meaning the investment grew as if it compounded at 13.2% each year." },
    { q: "How do I calculate ROI on a rental property?", a: "Annual ROI = (Annual rental income − Annual expenses) / Total investment × 100. Annual expenses include mortgage payments, insurance, maintenance, management, and property taxes. If you paid $200,000 for a property, collect $18,000/year in rent, and spend $10,000/year on expenses, your ROI is ($18,000 − $10,000) / $200,000 × 100 = 4%." },
    { q: "What is a negative ROI?", a: "A negative ROI means you lost money — the final value is less than your initial investment. Example: invest $5,000, end with $4,000. ROI = (4,000 − 5,000) / 5,000 × 100 = −20%. You lost 20% of your investment." },
    { q: "What is the difference between ROI and profit margin?", a: "ROI compares profit to the cost of investment. Profit margin compares profit to revenue (sales). A business can have high profit margins but low ROI if the upfront investment was very large. Both metrics are useful — ROI for capital allocation decisions, margin for pricing and operational efficiency." },
    { q: "How do I calculate marketing ROI?", a: "Marketing ROI = (Revenue generated by campaign − Campaign cost) / Campaign cost × 100. If you spent $2,000 on ads and generated $8,000 in attributed revenue: ROI = (8,000 − 2,000) / 2,000 × 100 = 300%. A marketing ROI above 100% is generally considered positive (every dollar spent returns more than $1 in revenue)." },
    { q: "Is a 10% ROI good?", a: "10% annually is historically in line with long-term S&P 500 returns, so yes — it's a solid benchmark for equity investments. For a short-term trade (e.g., 10% in 1 month), it's exceptional. For a 10-year real estate holding, it's on the low side. Always compare ROI to the risk taken and alternative uses of the capital." },
    { q: "What is the ROI of the S&P 500?", a: "The S&P 500 has returned approximately 10% per year on average over the past 50 years (before inflation). After inflation, the real return is closer to 7%. No single year matches this — returns vary widely from −38% (2008) to +38% (1995). The 10% figure is a long-run average for buy-and-hold investors." },
    { q: "How does ROI differ from IRR?", a: "ROI is a simple ratio of total profit to cost, ignoring when cash flows occur. IRR (Internal Rate of Return) is the discount rate that makes the net present value of all cash flows equal to zero — it accounts for the timing of cash flows. IRR is more accurate for multi-year projects with irregular cash flows; ROI is simpler and better for quick comparisons." },
]

useCalcSEO(
    "ROI Calculator — Return on Investment & CAGR",
    "Free ROI calculator. Enter your initial investment and final value to get ROI percentage, net profit, annualised return, and CAGR. Works for stocks, real estate, and business.",
    faqs
)

useHead({
    script: [{
        type: 'application/ld+json',
        innerHTML: JSON.stringify({
            '@context': 'https://schema.org',
            '@type': 'HowTo',
            name: 'How to Calculate ROI',
            description: 'Calculate return on investment, net profit, and annualised growth rate.',
            step: [
                { '@type': 'HowToStep', position: 1, name: 'Enter initial investment', text: 'Type the amount you originally invested or paid.' },
                { '@type': 'HowToStep', position: 2, name: 'Enter final value', text: 'Type the current or final value of the investment.' },
                { '@type': 'HowToStep', position: 3, name: 'Optionally enter time period', text: 'Enter the number of years to also get annualised ROI and CAGR.' },
                { '@type': 'HowToStep', position: 4, name: 'Click Calculate ROI', text: 'Results show ROI percentage, net profit, and annualised return metrics.' },
            ],
        }),
    }],
})
</script>
